<?php

namespace OCA\PreviewGenerator\Middleware;

use OC\Core\Controller\PreviewController;
use OC\OCS\Exception;
use OCA\PreviewGenerator\Exceptions\PreviewNotGeneratedYetException;
use OCP\AppFramework\Http\NotFoundResponse;
use OCP\IDBConnection;
use OCP\AppFramework\Middleware;

class PreviewMiddleware extends Middleware {

    /** @var IDBConnection */
    private $connection;

    public function __construct(IDBConnection $connection) {
        $this->connection = $connection;
    }

    public function afterException($controller, $methodName, \Exception $exception) {
        if ($exception instanceof PreviewNotGeneratedYetException) {
            return new NotFoundResponse();
        }
    }

    public function isFileRegisteredForPreviewGenerateByPlugin($fileId, $userId) : bool
    {
        $qb = $this->connection->getQueryBuilder();
        $qb->select('id')
            ->from('preview_generation')
            ->where(
                $qb->expr()->andX(
                    $qb->expr()->eq('uid', $qb->createNamedParameter($userId)),
                    $qb->expr()->eq('file_id', $qb->createNamedParameter($fileId))
                )
            )->setMaxResults(1);
        $cursor = $qb->execute();
        $inTable = $cursor->fetch() !== false;
        $cursor->closeCursor();

        // $fileId in queue to generate preview (raw exists in plugin database table)
        return $inTable;
    }

    public function beforeController($controller, $methodName)
    {
        if ($controller instanceof PreviewController) {
            $config = \OC::$server->getConfig();

            if (!$config->getSystemValue('enable_generated_previews_only', true)) {
                // Just return in case of disabled plugin setting. So previewManager can generate preview on the fly.
                return;
            }

            $root = \OC::$server->getRootFolder();
            $userId = \OC::$server->getUserSession()->getUser()->getUID();
            $request = \OC::$server->getRequest();
            $userFolder = $root->getUserFolder($userId);
            $userManager = \OC::$server->getUserManager();
            if (!$userManager->userExists($userId) || !$this->TryGetFileIdFromRequest($methodName, $userFolder, $request, $fileId))
            {
                // It is not case for us. Just return processing.
                return;
            }

            // Check that $fileId in order to be generated by plugin
            if ($this->isFileRegisteredForPreviewGenerateByPlugin($fileId, $userId)) {
                throw new PreviewNotGeneratedYetException();
            }
        }
    }

    /**
     * @param string $methodName
     * @param \OCP\Files\Folder $userFolder
     * @param \OCP\IRequest $request
     * @param $fileId
     */
    public function TryGetFileIdFromRequest(string $methodName, \OCP\Files\Folder $userFolder, \OCP\IRequest $request, &$fileId): bool
    {
        try{
            if ($methodName === 'getPreview') {
                $fileId = $userFolder->get($request->getParam('file'))->getId();
            } elseif ($methodName === 'getPreviewByFileId') {
                $fileId = $request->getParam('fileId');
            }
            return true;
        } catch (Exception $ex)
        {
            return false;
        }
    }
}